language: ruby
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
branches:
  only:
  - jekyll-inc-tut
script: rake tutorial:add[ropengov,sotkanet]
before_script:
  - sudo apt-get update
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package devtools
notifications:
  email:
    - one@example.com