inc:
  # Blog Information
  title:        "rOpenGov"
  subtitle:     "Algorithms for Computational Social Science and Digital Humanities"
  cover_image:  open-gov-cover.jpg
  about_image:  open-gov-cover.jpg
  logo:         logo.png

  # Fields for feed.xml
  name:		rOpenGov
  description:  "rOpenGov blog"  		
  url:		ropengov.github.io

  # Company information
  company:      rOpenGov
  url:          ropengov.github.io
  facebook:     
  twitter:      ropengov
  gplus:        '101183822199340201470'
  about:        about
  projects:     projects
  contribute:   contribute

  # Product Information
  product_link: 
  tagline:      

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  "ropengov"

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         true

  # Analytics     
  analytics:
    google: 
      id:       'UA-44262937-1'

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

gems: [jekyll-paginate, pygments]
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess', '.travis.yml']
exclude:     ['Rakefile', 'Gemfile', 'Gemfile.lock','CNAME', '*.sublime-workspace',
              '*.sublime-project']
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter: pygments

permalink:     pretty
#paginate_path: 'page:num'
#paginate: 10

markdown:      kramdown
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false

