# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
safe: false

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : rOpenGov
tagline: R ecosystem for open government data
author :
  name : Joona Lehtomäki
  email : joona.lehtomaki@gmail.com
  github : jlehtoma
  twitter : jlehtoma
users :
  leo : 
    role : admin
    name : Leo Lahti
    picture : LeoLahti.jpg
    email : leo.lahti@iki.fi
    homepage : http://www.iki.fi/Leo.Lahti
    github : antagomir
    twitter : antagomir
    googleplus : https://plus.google.com/101894517788603274082/
  juuso : 
    role : admin
    name : Juuso Parkkinen
    picture : JuusoParkkinen.jpg
    email : juuso.parkkinen@gmail.com
    homepage : http://ouzor.github.com/
    github : ouzor
    twitter : ouzor
    googleplus : https://plus.google.com/110816312923792859782/
  joona : 
    role : admin
    name : Joona Lehtomäki
    picture : JoonaLehtomaki.jpg
    email : joona.lehtomaki@gmail.com
    homepage : https://tuhat.halvi.helsinki.fi/portal/en/persons/joona-lehtomaki%287f6888ed-acb0-4c6a-aab5-bc54f26d0e61%29.html
    github : jlehtoma
    twitter : jlehtoma
    googleplus : https://plus.google.com/112885751907512172261/

projects:
  sorvi : 
    title : Finland
    url : http://louhos.github.com/sorvi/index.html
  rustfare :
    title : Russia
    url: http://markuskainu.fi/rustfare/index.html
  Grazwahl2012 :
    title : Austria
    url: https://github.com/skasberger/grazwahl2012
  osmar :
    title : OpenStreetMap
    url: http://osmar.r-forge.r-project.org/
  R packages :
    title : R packages
    url: packages.html


version: 0.1

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://ropengov.github.com/

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.2.9

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.com/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.com/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  BASE_PATH : false

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex: 
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change theme here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments :
    provider : disqus
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
   
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-8790224-9'

  # Settings for sharing helper. 
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false
    
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
  
  # How many items are shown in the news_collate array
  max_news_items : 5
