source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-assets'
gem 'maruku'
gem 'rake'
gem 'sass'
gem 'uglifier'
gem 'github-pages'
gem 'therubyracer'
gem 'rubyzip', :require => 'zip/zip'
gem 'table_print'