custom.theme <- ggplot2::theme(plot.title=element_text(face="bold", size=16),
                               axis.title.x=element_text(size=16),
                               axis.title.y=element_text(size=16),
                               axis.text.x=element_text(size=14),
                               axis.text.y=element_text(size=14),
                               axis.ticks = element_line(size = 1),
                               legend.text=element_text(size=12),
                               legend.title=element_text(size=14),
                               panel.background = element_rect(fill='white', 
                                                               colour='black'),
                               panel.grid.major.x = element_blank(), 
                               panel.grid.minor.x = element_blank(),
                               panel.grid.major.y = element_line(size = 0.5, 
                                                                 colour='lightgrey'),
                               panel.grid.minor.y = element_blank(),
                               legend.background = element_rect(fill='white', 
                                                                colour='white'),
                               strip.text.x = element_text(size = 14),
                               legend.key.width = unit(1.5, "cm"),
                               legend.key = element_blank())
